package com.expansivegroup.capital.capitalprojectsubmission;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ApproveConcept implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPROVECONCEPT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "APPROVECONCEPT_ID_SEQ", name = "APPROVECONCEPT_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.Boolean approve;

   private java.lang.String comment;

   public ApproveConcept()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Boolean getApprove()
   {
      return this.approve;
   }

   public void setApprove(java.lang.Boolean approve)
   {
      this.approve = approve;
   }

   public java.lang.String getComment()
   {
      return this.comment;
   }

   public void setComment(java.lang.String comment)
   {
      this.comment = comment;
   }

   public ApproveConcept(java.lang.Long id, java.lang.Boolean approve,
         java.lang.String comment)
   {
      this.id = id;
      this.approve = approve;
      this.comment = comment;
   }

}