package com.expansivegroup.capital.capitalprojectsubmission;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ProjectPrioritization implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECTPRIORITIZATION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PROJECTPRIORITIZATION_ID_SEQ", name = "PROJECTPRIORITIZATION_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.Integer revenuePrioritization;

   private java.lang.Integer productivityPrioritization;

   private java.lang.Integer productivityNonInventoryPrioritization;

   private java.lang.Integer qualityPrioritization;

   private java.lang.Integer regulatoryPrioritization;

   private java.lang.Integer safetyPrioritization;

   private java.lang.Integer operationsPrioritization;

   private java.lang.Integer prioritizationScore;

   public ProjectPrioritization()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getRevenuePrioritization()
   {
      return this.revenuePrioritization;
   }

   public void setRevenuePrioritization(java.lang.Integer revenuePrioritization)
   {
      this.revenuePrioritization = revenuePrioritization;
   }

   public java.lang.Integer getProductivityPrioritization()
   {
      return this.productivityPrioritization;
   }

   public void setProductivityPrioritization(
         java.lang.Integer productivityPrioritization)
   {
      this.productivityPrioritization = productivityPrioritization;
   }

   public java.lang.Integer getProductivityNonInventoryPrioritization()
   {
      return this.productivityNonInventoryPrioritization;
   }

   public void setProductivityNonInventoryPrioritization(
         java.lang.Integer productivityNonInventoryPrioritization)
   {
      this.productivityNonInventoryPrioritization = productivityNonInventoryPrioritization;
   }

   public java.lang.Integer getQualityPrioritization()
   {
      return this.qualityPrioritization;
   }

   public void setQualityPrioritization(java.lang.Integer qualityPrioritization)
   {
      this.qualityPrioritization = qualityPrioritization;
   }

   public java.lang.Integer getRegulatoryPrioritization()
   {
      return this.regulatoryPrioritization;
   }

   public void setRegulatoryPrioritization(
         java.lang.Integer regulatoryPrioritization)
   {
      this.regulatoryPrioritization = regulatoryPrioritization;
   }

   public java.lang.Integer getSafetyPrioritization()
   {
      return this.safetyPrioritization;
   }

   public void setSafetyPrioritization(java.lang.Integer safetyPrioritization)
   {
      this.safetyPrioritization = safetyPrioritization;
   }

   public java.lang.Integer getOperationsPrioritization()
   {
      return this.operationsPrioritization;
   }

   public void setOperationsPrioritization(
         java.lang.Integer operationsPrioritization)
   {
      this.operationsPrioritization = operationsPrioritization;
   }

   public java.lang.Integer getPrioritizationScore()
   {
      return this.prioritizationScore;
   }

   public void setPrioritizationScore(java.lang.Integer prioritizationScore)
   {
      this.prioritizationScore = prioritizationScore;
   }

   public ProjectPrioritization(java.lang.Long id,
         java.lang.Integer revenuePrioritization,
         java.lang.Integer productivityPrioritization,
         java.lang.Integer productivityNonInventoryPrioritization,
         java.lang.Integer qualityPrioritization,
         java.lang.Integer regulatoryPrioritization,
         java.lang.Integer safetyPrioritization,
         java.lang.Integer operationsPrioritization,
         java.lang.Integer prioritizationScore)
   {
      this.id = id;
      this.revenuePrioritization = revenuePrioritization;
      this.productivityPrioritization = productivityPrioritization;
      this.productivityNonInventoryPrioritization = productivityNonInventoryPrioritization;
      this.qualityPrioritization = qualityPrioritization;
      this.regulatoryPrioritization = regulatoryPrioritization;
      this.safetyPrioritization = safetyPrioritization;
      this.operationsPrioritization = operationsPrioritization;
      this.prioritizationScore = prioritizationScore;
   }

}