package com.expansivegroup.capital.capitalprojectsubmission;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Project implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECT_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PROJECT_ID_SEQ", name = "PROJECT_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String projectName;

   private java.lang.Integer projectExternalID;

   private java.lang.Integer jDEProject;

   private java.lang.String category;

   private java.lang.String sponsor;

   private java.lang.String manager;

   private java.lang.Boolean ITRequired;

   private java.lang.String description;

   public Project()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getProjectName()
   {
      return this.projectName;
   }

   public void setProjectName(java.lang.String projectName)
   {
      this.projectName = projectName;
   }

   public java.lang.Integer getProjectExternalID()
   {
      return this.projectExternalID;
   }

   public void setProjectExternalID(java.lang.Integer projectExternalID)
   {
      this.projectExternalID = projectExternalID;
   }

   public java.lang.Integer getjDEProject()
   {
      return this.jDEProject;
   }

   public void setjDEProject(java.lang.Integer jDEProject)
   {
      this.jDEProject = jDEProject;
   }

   public java.lang.String getCategory()
   {
      return this.category;
   }

   public void setCategory(java.lang.String category)
   {
      this.category = category;
   }

   public java.lang.String getSponsor()
   {
      return this.sponsor;
   }

   public void setSponsor(java.lang.String sponsor)
   {
      this.sponsor = sponsor;
   }

   public java.lang.String getManager()
   {
      return this.manager;
   }

   public void setManager(java.lang.String manager)
   {
      this.manager = manager;
   }

   public java.lang.Boolean getITRequired()
   {
      return this.ITRequired;
   }

   public void setITRequired(java.lang.Boolean ITRequired)
   {
      this.ITRequired = ITRequired;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public Project(java.lang.Long id, java.lang.String projectName,
         java.lang.Integer projectExternalID, java.lang.Integer jDEProject,
         java.lang.String category, java.lang.String sponsor,
         java.lang.String manager, java.lang.Boolean ITRequired,
         java.lang.String description)
   {
      this.id = id;
      this.projectName = projectName;
      this.projectExternalID = projectExternalID;
      this.jDEProject = jDEProject;
      this.category = category;
      this.sponsor = sponsor;
      this.manager = manager;
      this.ITRequired = ITRequired;
      this.description = description;
   }

}