package com.expansivegroup.capital.capitalprojectsubmission;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ProjectDetail implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECTDETAIL_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PROJECTDETAIL_ID_SEQ", name = "PROJECTDETAIL_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.Integer q1PlanSpend;

   private java.lang.Integer q2PlanSpend;

   private java.lang.Integer q3PlanSpend;

   private java.lang.Integer q4PlanSpend;

   private java.lang.Boolean dependencies;

   private java.lang.Integer totalPlanSpend;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   private com.expansivegroup.capital.capitalprojectsubmission.Project_Execution_Plan projectExecutionPlan;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   private com.expansivegroup.capital.capitalprojectsubmission.Project_Yearly_Spend projectYearSpend;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   private com.expansivegroup.capital.capitalprojectsubmission.ProjectPrioritization projectPrioritization;

   public ProjectDetail()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getQ1PlanSpend()
   {
      return this.q1PlanSpend;
   }

   public void setQ1PlanSpend(java.lang.Integer q1PlanSpend)
   {
      this.q1PlanSpend = q1PlanSpend;
   }

   public java.lang.Integer getQ2PlanSpend()
   {
      return this.q2PlanSpend;
   }

   public void setQ2PlanSpend(java.lang.Integer q2PlanSpend)
   {
      this.q2PlanSpend = q2PlanSpend;
   }

   public java.lang.Integer getQ3PlanSpend()
   {
      return this.q3PlanSpend;
   }

   public void setQ3PlanSpend(java.lang.Integer q3PlanSpend)
   {
      this.q3PlanSpend = q3PlanSpend;
   }

   public java.lang.Integer getQ4PlanSpend()
   {
      return this.q4PlanSpend;
   }

   public void setQ4PlanSpend(java.lang.Integer q4PlanSpend)
   {
      this.q4PlanSpend = q4PlanSpend;
   }

   public java.lang.Boolean getDependencies()
   {
      return this.dependencies;
   }

   public void setDependencies(java.lang.Boolean dependencies)
   {
      this.dependencies = dependencies;
   }

   public java.lang.Integer getTotalPlanSpend()
   {
      return this.totalPlanSpend;
   }

   public void setTotalPlanSpend(java.lang.Integer totalPlanSpend)
   {
      this.totalPlanSpend = totalPlanSpend;
   }

   public com.expansivegroup.capital.capitalprojectsubmission.Project_Execution_Plan getProjectExecutionPlan()
   {
      return this.projectExecutionPlan;
   }

   public void setProjectExecutionPlan(
         com.expansivegroup.capital.capitalprojectsubmission.Project_Execution_Plan projectExecutionPlan)
   {
      this.projectExecutionPlan = projectExecutionPlan;
   }

   public com.expansivegroup.capital.capitalprojectsubmission.Project_Yearly_Spend getProjectYearSpend()
   {
      return this.projectYearSpend;
   }

   public void setProjectYearSpend(
         com.expansivegroup.capital.capitalprojectsubmission.Project_Yearly_Spend projectYearSpend)
   {
      this.projectYearSpend = projectYearSpend;
   }

   public com.expansivegroup.capital.capitalprojectsubmission.ProjectPrioritization getProjectPrioritization()
   {
      return this.projectPrioritization;
   }

   public void setProjectPrioritization(
         com.expansivegroup.capital.capitalprojectsubmission.ProjectPrioritization projectPrioritization)
   {
      this.projectPrioritization = projectPrioritization;
   }

   public ProjectDetail(
         java.lang.Long id,
         java.lang.Integer q1PlanSpend,
         java.lang.Integer q2PlanSpend,
         java.lang.Integer q3PlanSpend,
         java.lang.Integer q4PlanSpend,
         java.lang.Boolean dependencies,
         java.lang.Integer totalPlanSpend,
         com.expansivegroup.capital.capitalprojectsubmission.Project_Execution_Plan projectExecutionPlan,
         com.expansivegroup.capital.capitalprojectsubmission.Project_Yearly_Spend projectYearSpend,
         com.expansivegroup.capital.capitalprojectsubmission.ProjectPrioritization projectPrioritization)
   {
      this.id = id;
      this.q1PlanSpend = q1PlanSpend;
      this.q2PlanSpend = q2PlanSpend;
      this.q3PlanSpend = q3PlanSpend;
      this.q4PlanSpend = q4PlanSpend;
      this.dependencies = dependencies;
      this.totalPlanSpend = totalPlanSpend;
      this.projectExecutionPlan = projectExecutionPlan;
      this.projectYearSpend = projectYearSpend;
      this.projectPrioritization = projectPrioritization;
   }

}