package com.expansivegroup.capital.capitalprojectsubmission;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Project_Yearly_Spend implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECT_YEARLY_SPEND_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PROJECT_YEARLY_SPEND_ID_SEQ", name = "PROJECT_YEARLY_SPEND_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.Integer planVersion;

   private java.util.Date startDate;

   private java.util.Date endDate;

   private java.lang.Integer spendPlan;

   private java.lang.String project;

   public Project_Yearly_Spend()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getPlanVersion()
   {
      return this.planVersion;
   }

   public void setPlanVersion(java.lang.Integer planVersion)
   {
      this.planVersion = planVersion;
   }

   public java.util.Date getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.util.Date startDate)
   {
      this.startDate = startDate;
   }

   public java.util.Date getEndDate()
   {
      return this.endDate;
   }

   public void setEndDate(java.util.Date endDate)
   {
      this.endDate = endDate;
   }

   public java.lang.Integer getSpendPlan()
   {
      return this.spendPlan;
   }

   public void setSpendPlan(java.lang.Integer spendPlan)
   {
      this.spendPlan = spendPlan;
   }

   public java.lang.String getProject()
   {
      return this.project;
   }

   public void setProject(java.lang.String project)
   {
      this.project = project;
   }

   public Project_Yearly_Spend(java.lang.Long id, java.lang.Integer planVersion,
         java.util.Date startDate, java.util.Date endDate,
         java.lang.Integer spendPlan, java.lang.String project)
   {
      this.id = id;
      this.planVersion = planVersion;
      this.startDate = startDate;
      this.endDate = endDate;
      this.spendPlan = spendPlan;
      this.project = project;
   }

}