package com.expansivegroup.capital.capitalprojectsubmission;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Project_Execution_Plan implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROJECT_EXECUTION_PLAN_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "PROJECT_EXECUTION_PLAN_ID_SEQ", name = "PROJECT_EXECUTION_PLAN_ID_GENERATOR")
   private java.lang.Long id;

   private java.util.Date dateProjectStart;

   private java.util.Date dateProjectEnd;

   private java.util.Date dateSpendStart;

   private java.util.Date dateSpendEnd;

   private java.util.Date dateCancelled;

   public Project_Execution_Plan()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getDateProjectStart()
   {
      return this.dateProjectStart;
   }

   public void setDateProjectStart(java.util.Date dateProjectStart)
   {
      this.dateProjectStart = dateProjectStart;
   }

   public java.util.Date getDateProjectEnd()
   {
      return this.dateProjectEnd;
   }

   public void setDateProjectEnd(java.util.Date dateProjectEnd)
   {
      this.dateProjectEnd = dateProjectEnd;
   }

   public java.util.Date getDateSpendStart()
   {
      return this.dateSpendStart;
   }

   public void setDateSpendStart(java.util.Date dateSpendStart)
   {
      this.dateSpendStart = dateSpendStart;
   }

   public java.util.Date getDateSpendEnd()
   {
      return this.dateSpendEnd;
   }

   public void setDateSpendEnd(java.util.Date dateSpendEnd)
   {
      this.dateSpendEnd = dateSpendEnd;
   }

   public java.util.Date getDateCancelled()
   {
      return this.dateCancelled;
   }

   public void setDateCancelled(java.util.Date dateCancelled)
   {
      this.dateCancelled = dateCancelled;
   }

   public Project_Execution_Plan(java.lang.Long id,
         java.util.Date dateProjectStart, java.util.Date dateProjectEnd,
         java.util.Date dateSpendStart, java.util.Date dateSpendEnd,
         java.util.Date dateCancelled)
   {
      this.id = id;
      this.dateProjectStart = dateProjectStart;
      this.dateProjectEnd = dateProjectEnd;
      this.dateSpendStart = dateSpendStart;
      this.dateSpendEnd = dateSpendEnd;
      this.dateCancelled = dateCancelled;
   }

}