package com.expansivegroup.capital.capitalprojectsubmission;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class SVPApproval implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SVPAPPROVAL_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "SVPAPPROVAL_ID_SEQ", name = "SVPAPPROVAL_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String commentOfSVP;

   private java.lang.Boolean approvalOfSVP;

   public SVPApproval()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCommentOfSVP()
   {
      return this.commentOfSVP;
   }

   public void setCommentOfSVP(java.lang.String commentOfSVP)
   {
      this.commentOfSVP = commentOfSVP;
   }

   public java.lang.Boolean getApprovalOfSVP()
   {
      return this.approvalOfSVP;
   }

   public void setApprovalOfSVP(java.lang.Boolean approvalOfSVP)
   {
      this.approvalOfSVP = approvalOfSVP;
   }

   public SVPApproval(java.lang.Long id, java.lang.String commentOfSVP,
         java.lang.Boolean approvalOfSVP)
   {
      this.id = id;
      this.commentOfSVP = commentOfSVP;
      this.approvalOfSVP = approvalOfSVP;
   }

}