package com.expansivegroup.declaration.investmentdeclaration;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class setDate implements java.io.Serializable
{
 ArrayList<String> emailIds = new ArrayList<>();
   static final long serialVersionUID = 1L;

   private java.util.Date startDate;

   private java.lang.Boolean startForm = false;

   private java.util.Date endDate;
   public static String toMail;

   public setDate()
   {
   }

   public java.util.Date getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.util.Date startDate)
   {
      this.startDate = startDate;
   }

   public java.lang.Boolean getStartForm()
   {
      return this.startForm;
   }

   public void setStartForm(java.lang.Boolean startForm)
   {

      this.startForm = startForm;
   }

   public java.util.Date getEndDate()
   {
      return this.endDate;
   }

   public void setEndDate(java.util.Date endDate)
   {
      this.endDate = endDate;
   }

   public setDate(java.util.Date startDate, java.lang.Boolean startForm,
         java.util.Date endDate)
   {
      this.startDate = startDate;
      this.startForm = startForm;
      this.endDate = endDate;

   }

   public String connectPost(String toMail) throws SQLException
   {
      Connection c = null;
      Statement stmt = null;
      try
      {
         Class.forName("org.postgresql.Driver");
      }
      catch (ClassNotFoundException e)
      {
         e.printStackTrace();
      }
//System.out.println("Before  Driver");
      c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/mytest", "postgres", "espl@2017");
    //  System.out.println("After  Driver");
      stmt = c.createStatement();
      ResultSet rs = stmt.executeQuery("SELECT * from Employee");
      while (rs.next())
      {
         emailIds.add(rs.getString("Email_id"));
       //  System.out.println(rs.getString("Email_id"));
      }
     toMail=emailIds.toString();
      toMail=toMail.replace(",", ";");
       toMail=toMail.substring(1, toMail.length()-1);
       toMail=toMail.replaceAll("\\s+","");
       System.out.println(toMail);
       return toMail;
    }
public setDate(java.util.ArrayList<java.lang.String> emailIds,
		java.util.Date startDate, java.lang.Boolean startForm,
		java.util.Date endDate)
		{
		this.emailIds = emailIds;
	    this.startDate = startDate;
	   this.startForm = startForm;
	   this.endDate = endDate;
        }
    
}