package com.expansivegroup.testdb;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class TestConnDb implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TESTCONNDB_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "TESTCONNDB_ID_SEQ", name = "TESTCONNDB_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.Integer empId;

   private java.lang.String empName;

   public TestConnDb()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Integer getEmpId()
   {
      return this.empId;
   }

   public void setEmpId(java.lang.Integer empId)
   {
      this.empId = empId;
   }

   public java.lang.String getEmpName()
   {
      return this.empName;
   }

   public void setEmpName(java.lang.String empName)
   {
      this.empName = empName;
   }

   public TestConnDb(java.lang.Long id, java.lang.Integer empId,
         java.lang.String empName)
   {
      this.id = id;
      this.empId = empId;
      this.empName = empName;
   }

}