package com.expansivegroup.category.selectinvestmentcategory;
import java.io.PrintStream;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import org.jbpm.formModeler.api.client.FormRenderContext;
import org.jbpm.formModeler.api.model.Field;
import org.jbpm.formModeler.core.config.SelectValuesProvider;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvestmentCategoryList implements SelectValuesProvider,Serializable {

    static final long serialVersionUID = 1L;

    public InvestmentCategoryList() {
    }
      public String getIdentifier()
  {
    return "InvestmentCategoryList";
  }
  
 public Map<String, String> getSelectOptions(Field field, String value, FormRenderContext formRenderContext, Locale locale)
  {
    HashMap<String, String> optionsList = new HashMap();
    Connection c = null;
    Statement stmt = null;
    try
    {
      //System.out.println("RestDataProvider.getSelectOptions() - " + field.getFieldName());
      Class.forName("org.postgresql.Driver");
      
      c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/mytest", "postgres", "espl@2017");
      
      stmt = c.createStatement();
     String sql = "select * from InvestmentCategory;";
      
      //System.out.println(sql);
      ResultSet rs = stmt.executeQuery(sql);
      while (rs.next()) {
        optionsList.put(rs.getString("Investment_category_id"), rs.getString("Investment_category_name"));
      }
      rs.close();
      c.close();
      stmt.close();
    }
    catch (Exception e)
    {
      e.printStackTrace();
    }
    return optionsList;
  }


}