package com.expansivegroup.email;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.util.Properties;
import java.util.Date;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import java.util.Properties;  
import javax.mail.*;  
import javax.mail.internet.*; 
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class sendEmail implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.Date startDate;
   private java.util.Date endDate;

   public sendEmail()
   {
   }

   public void send() throws SQLException
   {
		// TODO Auto-generated method stub
		Connection c=null;
		Statement stmt=null;
		String to=null;
		   try {
			   System.out.println("Before  class");
			Class.forName("org.postgresql.Driver");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		   System.out.println("Before  Driver");
	         c = DriverManager.getConnection("jdbc:postgresql://localhost:5432/mytest", "postgres", "espl@2017");
	         System.out.println("After  Driver");
	         stmt = c.createStatement();
	         ResultSet rs= stmt.executeQuery("SELECT * from Employee");
	         while(rs.next())
	         {
	         System.out.println(rs.getString("Email_id"));
	         to=rs.getString("Email_id");
	         String host="smtp.gmail.com";  
	   	   	 String user="sanyogita.londhe@gmail.com";//change accordingly  
	   	   	 String password="$sanyogita";//change accordingly  
	   	   	//  String to="sanyogitalondhe19@gmail.com";//change accordingly  
	   	   	 String from = "sanyogita.londhe@gmail.com";
	   	   	 String subject="Investment Declaration";
	   	   	 String text= "Please fill Investment declaration forms";
	   	   	  boolean sessionDebug = false;
	   	   	  
	   	   	  
	   	   	    try {   //Get the session object  
		   	   	   Properties props = new Properties();
		   	   	   props.setProperty("mail.smtp.host",host);
		   	   	   props.put("mail.smtp.starttls.enable", "true"); 
		   	   	   props.put("mail.smtp.host",host);  
		   	   	   props.put("mail.smtp.auth","true");
		   	   	   props.put("mail.smtp.port","587" ); 
		   	   	   props.put("mail.smtp.starttls.required","true" ); 
		   	   	  
		   	   	 //  java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
		   	   	   Session session = Session.getDefaultInstance(props, null);
		   	   	   session.setDebug(sessionDebug);
		   	   	   Message msg= new MimeMessage(session);
		   	   	   msg.setFrom(new InternetAddress(from));
		   	   	   InternetAddress [] address= {new InternetAddress(to)};
		   	   	   msg.setRecipients(Message.RecipientType.TO, address);
		   	   	   msg.setSubject(subject);
		   	   	   msg.setSentDate(new Date());
		   	   	   msg.setText(text);
		   	   	  Transport transport=session.getTransport("smtp");
		   	   	  transport.connect(host, user, password);
		   	   	  transport.sendMessage(msg, msg.getAllRecipients());
		   	   	  transport.close();
		   	   	  System.out.println("Message Send Successful");
		   	   	   //Compose the message  
	   	   	         } 
	   	   	  catch (MessagingException e)
	   	   	    {
	   	   	    	e.printStackTrace();
	   	   	     System.out.println(e); 
	   	   	    }  

	        	 }
	        
	   }

   public java.util.Date getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.util.Date startDate)
   {
      this.startDate = startDate;
   }

   public java.util.Date getEndDate()
   {
      return this.endDate;
   }

   public void setEndDate(java.util.Date endDate)
   {
      this.endDate = endDate;
   }

   public sendEmail(java.util.Date startDate, java.util.Date endDate)
   {
      this.startDate = startDate;
      this.endDate = endDate;
   }

}